site_name: Actividades
dev_addr: \x68\x74\x74\x70\x3a\x2f\x2f\x31\x32\x37\x2e\x30\x2e\x30\x2e\x31\x3a\x38\x30\x30\x31
# site_url: 
# repo_url: 
# repo_name: <i class="fa fa-git"></i>

theme:
    name: mkdocs
    custom_dir: resources/
extra_css:
    - css/page.css
nav:
    - Individuales:
        - Actividad 1: individual/actividad1.md
        - Actividad 2: todo.md
    - Colaborativas:
        - Actividad 1: todo.md
copyright: ©GMDXX
site_author: GMDXX
